on:
  push:
    branches:
      - main

permissions:
  checks: write
  contents: write
  pull-requests: write

name: Release

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Create Tag & Changelog
        uses: google-github-actions/release-please-action@v4
        id: release
      - uses: actions/checkout@main
      - name: Create Release Artifact
        if: ${{ steps.release.outputs.release_created }}
        uses: thedoctor0/zip-release@0.7.6
        with:
          type: 'zip'
          filename: 'resonate-${{ steps.release.outputs.tag_name }}.zip'
          path: 'addons'
      - name: Publish Release
        if: ${{ steps.release.outputs.release_created }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ steps.release.outputs.tag_name }} resonate-${{ steps.release.outputs.tag_name }}.zip
